---
title: "kyoto restaurant"
output: html_document
---
```{r}
pkgs = c("units","lucr","shinyWidgets","xml2","leaflet","htmltools")
for (pkg in pkgs){
  if (!(pkg %in% installed.packages()[, 1])){
    install.packages(pkg)
  }
}
library(dplyr)
library(tidyr)
library(stringr)
library(units)
library("lucr")
library(shiny)
library(shinythemes)
library(shinyWidgets)
library(leaflet)
library("xml2")
library(htmltools)
```

Load CSV File 
```{r}
Kyoto_Restaurant_raw = read.csv("Kyoto_Restaurant_Info.csv")
```

Clean Data
```{r}
#function
## clean function
clean_price = function(price){
  str_remove_all(price,"￥") %>% 
    str_replace("～","-") %>% 
    str_replace("^ -","0-") %>% 
    str_replace("30000-","30000+")
}
#clean_category =function(category){
#  category = category %>% 
#    str_replace("Bistro","Bar") %>%
#    str_replace("Beer","Beer Bar") %>%
#    str_replace("Beer\\sBar","Beer Bar") %>%
#    str_replace("Beer\\sgarden","Beer Bar")%>%
#    str_replace("Café / coffee shop (and others)","Cafe") %>% 
#    str_replace("Traditional Café","Cafe") %>%
#    str_replace("Champon Noodle","Ramen") %>% 
#    str_replace("Chinese","Chinese") %>% 
#    str_replace("Chinese hot pot / fire pot", "Chinese hot pot") %>% 
#    str_replace("Dandan noodles","Chinese") %>% 
#    str_replace("Dumplings","Chinese") %>% 
#    str_replace("Genghis Khan (BBQ Rum)","hot pot") %>% 
#    str_replace("Horumo\\s(BBQ Offel)","Japanese BBQ") %>% 
#    str_replace("Izakaya\\s(other)", "Izakaya (Tavern)") %>% 
#    str_replace("Korean\\scuisine","Korea") %>% 
#    str_replace("Modern\\sFrench","French") %>% 
#    str_replace("Motsu Nabe (Offel Hot Pot)","Hot Pot") %>% 
#    str_replace("Pork\\s","") %>% 
#    str_replace(" (Japanese Steamboat)","") %>% 
#    str_replace("Stand\\sBar", "Bar") %>% 
#    str_replace("Standing\\sstyle\\ss","S") %>% 
#    str_replace("Sukiyaki","Japanese hot pot") %>% 
#    str_replace("Thailand\\scooking", "Thailand") %>% 
#    str_replace("Udon\\sSuki","Udon") %>% 
#    str_replace("Western\\s(Others)","Western") %>% 
#    str_replace("Western\\sCuisine","Western") %>% 
#    str_replace("Western\sFood\\s(Other)","Western") %>% 
#    str_replace("Wine\\sbar","Bar")
#}

Kyoto_Restaurant =Kyoto_Restaurant_raw %>% 
  mutate(
    Station = as.factor(Station),
    FirstCategory = as.factor(FirstCategory),
    SecondCategory = as.factor(SecondCategory),
    Category = FirstCategory %>% as.factor(),
    DinnerPrice = clean_price(DinnerPrice) %>% as.factor(),
    LunchPrice  = clean_price(LunchPrice) %>% addNA() %>% as.factor())

leaflet() %>%
  addTiles() %>%
  setView(lng = 135.77, lat = 35.01, zoom = 15) %>%
  addMarkers(lng=135.77, lat=35.01 ,popup = "CC")
```

```{r}
shinyApp(
  ui = fluidPage(
    theme = shinytheme('united'),
    titlePanel(h4("Kyoto Restaurant")),
    sidebarLayout(
      sidebarPanel(
        #Select Station
        pickerInput("station", h5("Select the station closest to your ideal restaurant"),
                    choices = levels(Kyoto_Restaurant$Station),options = list(`actions-box` = TRUE),multiple = TRUE),
        #Select Food Category
        selectInput("first_category",label = h5("Select the food category"),
                    choices = levels(Kyoto_Restaurant$FirstCategory),multiple = TRUE),
        #Select Second Food Category
        checkboxInput("choose_second_category","Optional: select the second food category"),
        conditionalPanel(
          "input.choose_second_category == true",
          selectInput("second_category",label = h5("Select the second food cetegory"),
                      choices = levels(Kyoto_Restaurant$SecondCategory))),
        #Choose Dinner or Lunch
        radioButtons("dinner_or_lunch",label =h5(NULL),choices = list("Dinner","Lunch")),
        #Select Dinner Price
        conditionalPanel(
          "input.dinner_or_lunch =='Dinner'",
          radioButtons("price_rough",label=h5("Select the Price"),
                     choices = list("￥","￥￥", "￥￥￥", "￥￥￥￥","￥￥￥￥￥"))),
        conditionalPanel(
          "input.dinner_or_lunch =='Dinner' && input.price_rough == '￥'",
          checkboxGroupInput("price_range1", label = h5("Select the price range(JPY)"),
                             choices = levels(Kyoto_Restaurant$DinnerPrice)[1:2])),
        conditionalPanel(
          "input.dinner_or_lunch =='Dinner' && input.price_rough == '￥￥'",
          checkboxGroupInput("price_range2", label = h5("Select the price range(JPY)"), 
                             choices = levels(Kyoto_Restaurant$DinnerPrice)[c(5,7,9)])),
        conditionalPanel(
          "input.dinner_or_lunch =='Dinner' && input.price_rough == '￥￥￥'",
          checkboxGroupInput("price_range3", label = h5("Select the price range(JPY)"), 
                             choices = levels(Kyoto_Restaurant$DinnerPrice)[10:12])),
        conditionalPanel(
          "input.dinner_or_lunch =='Dinner' && input.price_rough == '￥￥￥￥'",
          checkboxGroupInput("price_range4", label = h5("Select the price range(JPY)"),
                             choices = levels(Kyoto_Restaurant$DinnerPrice)[3:4])),
        conditionalPanel(
          "input.dinner_or_lunch =='Dinner' && input.price_rough == '￥￥￥￥￥'",
          checkboxGroupInput("price_range5", label = h5("Select the price range(JPY)"), 
                             choices = levels(Kyoto_Restaurant$DinnerPrice)[c(6,8)])),
        #Select Dinner Rating
        conditionalPanel(
          "input.dinner_or_lunch =='Dinner'",
          sliderInput("dinner_rating",h5("Minimum rating"), min = as.numeric(3), max = as.numeric(4.16),value = 3.0)),
        #Select Lunch Price
        conditionalPanel(
          "input.dinner_or_lunch =='Lunch'",
          radioButtons("price_rough_lunch",label=h5("Select the Price"),
                     choices = list("￥","￥￥", "￥￥￥", "￥￥￥￥"))),
        conditionalPanel(
          "input.dinner_or_lunch =='Lunch' && input.price_rough_lunch == '￥'",
          checkboxGroupInput("price_range1_l", label = h5("Select the price range(JPY)"),
                             choices = levels(Kyoto_Restaurant$LunchPrice)[1:2])),
        conditionalPanel(
          "input.dinner_or_lunch =='Lunch' && input.price_rough_lunch == '￥￥'",
          checkboxGroupInput("price_range2_l", label = h5("Select the price range(JPY)"), 
                             choices = levels(Kyoto_Restaurant$LunchPrice)[5:7])),
        conditionalPanel(
          "input.dinner_or_lunch =='Lunch' && input.price_rough_lunch == '￥￥￥'",
          checkboxGroupInput("price_range3_l", label = h5("Select the price range(JPY)"), 
                             choices = levels(Kyoto_Restaurant$LunchPrice)[8:10])),
        conditionalPanel(
          "input.dinner_or_lunch =='Lunch' && input.price_rough_lunch == '￥￥￥￥'",
          checkboxGroupInput("price_range4_l", label = h5("Select the price range(JPY)"),
                             choices = levels(Kyoto_Restaurant$LunchPrice)[3:4])),
        #Select Lunch Rating
        conditionalPanel(
          "input.dinner_or_lunch =='Lunch'",
          sliderInput("lunch_rating",h5("Minimum rating"), min = as.numeric(3), max = as.numeric(4.11),value = 3.0)),
        #Add an Action Button
        actionButton("search", h5("Search"))
      ),
      mainPanel(
        leafletOutput("leaf", width = "100%", height = 240),
        tableOutput("restaurant")
      )
    )
  ),
  
  
  server = function(input, output, session){
    # Filter the restaurant, returning a data frame
    restaurants = eventReactive(input$search,{
      ## Generate temp variables for input values
      station = input$station
      first_category = input$first_category
      second_category = input$second_category
      
      rough_price = input$price_rough
      if (rough_price == "￥" )
        dinner_price = input$price_range1
      if (rough_price == "￥￥")
        dinner_price = input$price_range2
      if (rough_price == "￥￥￥")
        dinner_price = input$price_range3
      if (rough_price =="￥￥￥￥")
        dinner_price = input$price_range4
      if (rough_price == "￥￥￥￥￥")
        dinner_price = input$price_range5
      dinner_rating = input$dinner_rating
        
      rough_price_lunch = input$price_rough_lunch
      if (rough_price_lunch == "￥" )
        lunch_price = input$price_range1_l
      if (rough_price_lunch == "￥￥")
        lunch_price = input$price_range2_l
      if (rough_price_lunch == "￥￥￥")
        lunch_price = input$price_range3_l
      if (rough_price_lunch =="￥￥￥￥")
        lunch_price = input$price_range4_l
      lunch_rating = input$lunch_rating
      
      ## Apply filters
      rd = Kyoto_Restaurant %>% 
        filter(
          Station %in% station,
          FirstCategory %in% first_category,
          DinnerPrice %in% dinner_price,
          DinnerRating >=dinner_rating) 
      
      rl = Kyoto_Restaurant %>% 
        filter(
          Station %in% station,
          FirstCategory %in% first_category,
          LunchPrice %in% lunch_price,
          LunchRating >=lunch_rating) 
      
      if (input$dinner_or_lunch == "Dinner")
        r = rd
      if (input$dinner_or_lunch == "Lunch")
        r = rl
      
      # Optional filter
      if (input$choose_second_category ==TRUE){
        r = r %>% 
          filter(SecondCategory == second_category) %>% 
          arrange()}
      r = as.data.frame(r)
   })
    
    #Set output of a restaurant table
    output$restaurant = renderTable({
      output_restaurants = restaurants() %>% 
        select(Name,JapaneseName,DinnerPrice,LunchPrice)
      })
    #Set output of a map indicating the selected restaurants
    ##setView makes the argument as the center point of the map, so may adjustable to change
    ##adjust the exhibiting size of the map if possible
    ##need set links between the restaurants and the markers
    ##if there is no restaurants matching the parameters, it will show nothing for the table
    ##however, since it's empty, it will indicate error for the map
    output$leaf = renderLeaflet({
      leaflet(restaurants()) %>%
        setView(lng = restaurants()[1,14], lat = restaurants()[1,13],zoom = 50) %>% 
        addTiles() %>%
        addMarkers(~Long, ~Lat, label = ~Name)})
    
  }
)
```



